# Generated by Django 3.0.7 on 2020-06-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Posts'),
        ),
    ]
